import React, { useState, useEffect } from 'react';
import { FileText, Copy, Share } from '@phosphor-icons/react';

export default function ExportRevolution() {
  const [canShare, setCanShare] = useState(false);
  const [copySuccess, setCopySuccess] = useState(false);

  useEffect(() => {
    setCanShare(!!navigator.share);
  }, []);

  const manifestoText = `
HACK CLUB COMMUNIST PARTY MANIFESTO

WORKERS OF THE CODE, UNITE!

We, the members of the Hack Club Communist Party (HCP), hereby declare our commitment to the following principles:

1. All repositories shall be open to the people
2. Every pull request shall be reviewed equally
3. The means of code production shall belong to the programming proletariat
4. Knowledge and documentation shall be freely shared among all comrades
5. The banking oligarchy's grip on our digital infrastructure must end

JOIN US IN THE DIGITAL REVOLUTION!

This message was generated by a fellow comrade of the HCP
(This is satirical content - not affiliated with actual Hack Club)
`;

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(manifestoText);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const shareRevolution = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'HCP Manifesto',
          text: manifestoText,
          url: window.location.href,
        });
      } catch (err) {
        console.error('Failed to share:', err);
      }
    }
  };

  return (
    <div className="my-12 border-2 border-accent-9 p-6 rounded bg-black">
      <div className="flex items-center gap-2 mb-6">
        <FileText size={32} className="text-accent-9" weight="fill" />
        <h2 className="text-2xl font-bold revolutionary-text">EXPORT THE REVOLUTION</h2>
      </div>

      <div className="mb-6">
        <h3 className="text-xl font-bold mb-2 text-accent-11">REVOLUTIONARY MANIFESTO</h3>
        <pre className="bg-gray-900 p-4 rounded text-gray-300 whitespace-pre-wrap font-mono text-sm">
          {manifestoText}
        </pre>
      </div>

      <div className="flex gap-4 justify-center">
        <button
          onClick={copyToClipboard}
          className="flex items-center gap-2 bg-accent-9 hover:bg-red-800 text-white font-bold py-2 px-4 rounded revolutionary-button transition-colors"
        >
          <Copy size={24} />
          {copySuccess ? 'COPIED!' : 'COPY MANIFESTO'}
        </button>
        {canShare && (
          <button
            onClick={shareRevolution}
            className="flex items-center gap-2 bg-accent-9 hover:bg-red-800 text-white font-bold py-2 px-4 rounded revolutionary-button transition-colors"
          >
            <Share size={24} />
            SHARE REVOLUTION
          </button>
        )}
      </div>
    </div>
  );
}